<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-23T13:45:35 IST" name="EmergingServices-TMS" finished-at="2022-12-23T13:46:15 IST" duration-ms="40231">
    <groups>
    </groups>
    <test started-at="2022-12-23T13:45:35 IST" name="AIMS_AddAssetTest" finished-at="2022-12-23T13:46:15 IST" duration-ms="40231">
      <class name="TestCases.addAssetTest">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:TestCases.addAssetTest@37858383]" started-at="2022-12-23T13:45:35 IST" name="setUp" finished-at="2022-12-23T13:45:41 IST" duration-ms="6240" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLoginTest()[pri:1, instance:TestCases.addAssetTest@37858383]" started-at="2022-12-23T13:45:41 IST" name="verifyLoginTest" finished-at="2022-12-23T13:45:52 IST" duration-ms="10500" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginTest -->
        <test-method signature="validateLogoTest()[pri:2, instance:TestCases.addAssetTest@37858383]" started-at="2022-12-23T13:45:52 IST" name="validateLogoTest" finished-at="2022-12-23T13:45:52 IST" duration-ms="58" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLogoTest -->
        <test-method signature="validateAddAsset()[pri:3, instance:TestCases.addAssetTest@37858383]" started-at="2022-12-23T13:45:52 IST" name="validateAddAsset" finished-at="2022-12-23T13:46:15 IST" duration-ms="23407" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Asset- 22 Dec 22-1] but found [Asset- 22 Dec 22-2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Asset- 22 Dec 22-1] but found [Asset- 22 Dec 22-2]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at TestCases.addAssetTest.validateAddAsset(addAssetTest.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateAddAsset -->
      </class> <!-- TestCases.addAssetTest -->
    </test> <!-- AIMS_AddAssetTest -->
  </suite> <!-- EmergingServices-TMS -->
</testng-results>
